### ISSUE TITLE
undefined: strings.LastIndexByte

### ISSUE THREAD

**Issue by Dr-Terrible** [dvyukov/go-fuzz#115]
Apparently `go-fuzz` (snapshot 241d865) doesn't build anymore with go1.4.2, while it builds correctly with go1.5+. Here is the compilation error:

```sh
# github.com/dvyukov/go-fuzz/go-fuzz-build
go-fuzz-build/cover.go:292: undefined: strings.LastIndexByte
```

and here is the output of my `go env`:

```sh
GOARCH="amd64"
GOBIN="/home/dr-terrible/workspaces/go/bin"
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/dr-terrible/workspaces/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
CC="x86_64-pc-linux-gnu-gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="0"
```

**Comment by dgryski** [comment]
Known issue.  #112 was closed with "won't fix". Please upgrade to 1.5.

**Comment by Dr-Terrible** [comment]
Thank you for the clarification, @dgryski . I was tricked by #101 into believing that go1.4 was supported in some way. My apology for the extra noise; I'll close the issue.
